2024-10-15 16:03:08,157 (97105/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-15 16:03:08,157 (97105/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-15 16:03:10,562 (97105/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "more-backend"\n'
2024-10-15 16:03:13,480 (97128/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-15 16:03:13,480 (97128/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-15 16:04:11,181 (97199/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-15 16:04:11,181 (97199/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-15 16:10:34,668 (97199/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type=INSERAT limit 2', error: UndefinedColumn('column "inserat" does not exist\nLINE 1: select * from process_record where process_type=INSERAT limi...\n                                                        ^')
2024-10-15 16:10:34,672 (97199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "inserat" does not exist\nLINE 1: select * from process_record where process_type=INSERAT limi...\n                                                        ^\n'
2024-10-15 16:10:46,196 (97199/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type=INSERAT limit 2', error: UndefinedColumn('column "inserat" does not exist\nLINE 1: select * from process_record where process_type=INSERAT limi...\n                                                        ^')
2024-10-15 16:10:46,197 (97199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "inserat" does not exist\nLINE 1: select * from process_record where process_type=INSERAT limi...\n                                                        ^\n'
2024-10-15 16:10:54,434 (97199/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type=BEWERBUNG limit 2', error: UndefinedColumn('column "bewerbung" does not exist\nLINE 1: select * from process_record where process_type=BEWERBUNG li...\n                                                        ^')
2024-10-15 16:10:54,435 (97199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "bewerbung" does not exist\nLINE 1: select * from process_record where process_type=BEWERBUNG li...\n                                                        ^\n'
2024-10-15 16:11:02,229 (97199/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type="BEWERBUNG" limit 2', error: UndefinedColumn('column "BEWERBUNG" does not exist\nLINE 1: select * from process_record where process_type="BEWERBUNG" ...\n                                                        ^')
2024-10-15 16:11:02,230 (97199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "BEWERBUNG" does not exist\nLINE 1: select * from process_record where process_type="BEWERBUNG" ...\n                                                        ^\n'
2024-10-15 16:12:09,243 (97199/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type=BEWERBUNG', error: UndefinedColumn('column "bewerbung" does not exist\nLINE 1: select * from process_record where process_type=BEWERBUNG\n                                                        ^')
2024-10-15 16:12:09,244 (97199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "bewerbung" does not exist\nLINE 1: select * from process_record where process_type=BEWERBUNG\n                                                        ^\n'
2024-10-15 16:13:24,658 (97199/MainThread) pgcli.main ERROR - sql: "select * from process_record where process_type='INSERAT' limit 2;", error: StopIteration()
2024-10-15 16:13:24,660 (97199/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-15 17:22:58,200 (99850/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-15 17:22:58,200 (99850/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-16 09:48:21,644 (75231/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-16 09:48:21,645 (75231/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-16 09:49:22,401 (75231/MainThread) pgcli.pgexecute ERROR - sql: 'select * from process_record where process_type=TERMINATION limit 5', error: UndefinedColumn('column "termination" does not exist\nLINE 1: select * from process_record where process_type=TERMINATION ...\n                                                        ^')
2024-10-16 09:49:22,402 (75231/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "termination" does not exist\nLINE 1: select * from process_record where process_type=TERMINATION ...\n                                                        ^\n'
2024-10-16 09:54:28,414 (75231/MainThread) pgcli.main ERROR - sql: "select status from process_record where process_type='termination' limit 5;", error: StopIteration()
2024-10-16 09:54:28,416 (75231/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-16 10:11:07,511 (75231/MainThread) pgcli.main ERROR - sql: "select distinct status from process_record where process_type='INSERAT';", error: StopIteration()
2024-10-16 10:11:07,512 (75231/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-16 17:16:00,685 (23428/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-16 17:16:00,686 (23428/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-16 17:16:00,691 (23428/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-16 17:16:08,353 (23454/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-16 17:16:08,353 (23454/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-16 17:23:47,308 (23454/MainThread) pgcli.main ERROR - sql: "select * from process_record where process_type='TERMINATION' and status='WAITING' limit 30;", error: StopIteration()
2024-10-16 17:23:47,310 (23454/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-16 17:23:56,253 (23454/MainThread) pgcli.main ERROR - sql: "select * from process_record where process_type='TERMINATION' and execution_state='WAITING' limit 30;", error: StopIteration()
2024-10-16 17:23:56,253 (23454/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-17 11:29:46,384 (70185/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-17 11:29:46,384 (70185/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-17 11:30:38,435 (70185/MainThread) pgcli.pgexecute ERROR - sql: 'select * from _search_traces limit 5 order by executed_at', error: SyntaxError('syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at\n                                             ^')
2024-10-17 11:30:38,437 (70185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at\n                                             ^\n'
2024-10-17 11:30:59,445 (70185/MainThread) pgcli.pgexecute ERROR - sql: 'select * from _search_traces limit 5 order by executed_at', error: SyntaxError('syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at\n                                             ^')
2024-10-17 11:30:59,446 (70185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at\n                                             ^\n'
2024-10-17 11:31:29,486 (70185/MainThread) pgcli.pgexecute ERROR - sql: 'select * from _search_traces limit 5 order by executed_at asc', error: SyntaxError('syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at as...\n                                             ^')
2024-10-17 11:31:29,486 (70185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "order"\nLINE 1: select * from _search_traces limit 5 order by executed_at as...\n                                             ^\n'
2024-10-17 11:55:53,186 (70185/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2024-10-17 11:55:53,187 (70185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2024-10-17 11:57:50,292 (71191/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-17 11:57:50,293 (71191/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-17 11:58:00,763 (71191/MainThread) pgcli.pgexecute ERROR - sql: 'select WITH', error: SyntaxError('syntax error at or near "WITH"\nLINE 1: select WITH\n               ^')
2024-10-17 11:58:00,765 (71191/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "WITH"\nLINE 1: select WITH\n               ^\n'
2024-10-17 12:52:35,173 (4309/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-17 12:52:35,173 (4309/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-17 12:52:37,254 (4309/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 741, in connect\n    passwd = click.prompt(\n        "Password for %s" % user,\n    ...<2 lines>...\n        type=str,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/click/termui.py", line 164, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/click/termui.py", line 147, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2024-10-18 09:31:07,354 (51801/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 09:31:07,354 (51801/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 09:49:11,788 (55263/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 09:49:11,789 (55263/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 09:51:22,667 (55263/MainThread) pgcli.pgexecute ERROR - sql: "select distinct i.processRecord.einheit.bauteil.bezirk from EinheitInseratProcess i where i.processRecord.executionState = 'RUNNING'", error: UndefinedTable('relation "einheitinseratprocess" does not exist\nLINE 1: ...tinct i.processRecord.einheit.bauteil.bezirk from EinheitIns...\n                                                             ^')
2024-10-18 09:51:22,670 (55263/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "einheitinseratprocess" does not exist\nLINE 1: ...tinct i.processRecord.einheit.bauteil.bezirk from EinheitIns...\n                                                             ^\n'
2024-10-18 09:52:51,449 (55263/MainThread) pgcli.pgexecute ERROR - sql: 'select distinct i.process_recotd.einheit.bauteil.bezird from einheit_inserat_process i', error: SyntaxError('improper qualified name (too many dotted names): i.process_recotd.einheit.bauteil.bezird\nLINE 1: select distinct i.process_recotd.einheit.bauteil.bezird from...\n                        ^')
2024-10-18 09:52:51,451 (55263/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: improper qualified name (too many dotted names): i.process_recotd.einheit.bauteil.bezird\nLINE 1: select distinct i.process_recotd.einheit.bauteil.bezird from...\n                        ^\n'
2024-10-18 09:53:08,066 (55263/MainThread) pgcli.pgexecute ERROR - sql: 'select distinct i.process_recotd.einheit.bauteil.bezirk from einheit_inserat_process i', error: SyntaxError('improper qualified name (too many dotted names): i.process_recotd.einheit.bauteil.bezirk\nLINE 1: select distinct i.process_recotd.einheit.bauteil.bezirk from...\n                        ^')
2024-10-18 09:53:08,067 (55263/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: improper qualified name (too many dotted names): i.process_recotd.einheit.bauteil.bezirk\nLINE 1: select distinct i.process_recotd.einheit.bauteil.bezirk from...\n                        ^\n'
2024-10-18 09:58:25,394 (55263/MainThread) pgcli.main ERROR - sql: 'select * from ort_suche_suggestion limit 3;', error: StopIteration()
2024-10-18 09:58:25,397 (55263/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-18 09:58:55,380 (55263/MainThread) pgcli.main ERROR - sql: 'select * from inserat_orte_oesterreich limit 5;', error: StopIteration()
2024-10-18 09:58:55,381 (55263/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-18 09:59:50,307 (55263/MainThread) pgcli.main ERROR - sql: 'select * from einheit_inserat_process limit 5;', error: StopIteration()
2024-10-18 09:59:50,308 (55263/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-18 10:02:27,669 (56834/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:02:27,669 (56834/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 10:05:26,161 (57318/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:05:26,161 (57318/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 10:05:26,176 (57318/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: could not receive data from server: Connection refused\n'
2024-10-18 10:05:33,205 (57351/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:05:33,205 (57351/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 10:05:33,217 (57351/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: could not receive data from server: Connection refused\n'
2024-10-18 10:05:46,183 (57412/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:05:46,183 (57412/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 10:05:55,398 (57412/MainThread) pgcli.pgexecute ERROR - sql: 'select * from einheit_inserat_process limit 5', error: UndefinedTable('relation "einheit_inserat_process" does not exist\nLINE 1: select * from einheit_inserat_process limit 5\n                      ^')
2024-10-18 10:05:55,400 (57412/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "einheit_inserat_process" does not exist\nLINE 1: select * from einheit_inserat_process limit 5\n                      ^\n'
2024-10-18 10:07:44,143 (57706/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:07:44,143 (57706/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 10:09:21,219 (57893/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 10:09:21,219 (57893/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 11:19:54,550 (67979/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 11:19:54,551 (67979/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 11:19:59,310 (67979/MainThread) pgcli.pgexecute ERROR - sql: 'ALTER TABLE inserat_orte_oesterreich DROP COLUMN integer_id', error: UndefinedColumn('column "integer_id" of relation "inserat_orte_oesterreich" does not exist')
2024-10-18 11:19:59,315 (67979/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "integer_id" of relation "inserat_orte_oesterreich" does not exist\n'
2024-10-18 11:21:42,558 (68198/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 11:21:42,558 (68198/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 11:21:50,269 (68198/MainThread) pgcli.pgexecute ERROR - sql: 'ALTER TABLE inserat_orte_oesterreich DROP COLUMN integer_id', error: UndefinedColumn('column "integer_id" of relation "inserat_orte_oesterreich" does not exist')
2024-10-18 11:21:50,271 (68198/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "integer_id" of relation "inserat_orte_oesterreich" does not exist\n'
2024-10-18 13:44:20,280 (56834/MainThread) pgcli.pgexecute ERROR - sql: 'select * from einheit_inserat_process limit 5', error: OperationalError('consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.')
2024-10-18 13:44:20,284 (56834/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-10-18 13:44:20,284 (56834/MainThread) pgcli.main ERROR - sql: 'select * from einheit_inserat_process limit 5;', error: OperationalError('consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.')
2024-10-18 13:44:20,286 (56834/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-10-18 13:47:38,392 (82268/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 13:47:38,392 (82268/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-18 15:42:48,056 (6730/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-18 15:42:48,056 (6730/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-21 09:36:03,867 (56834/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-21 09:36:03,868 (56834/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-21 09:42:44,018 (56834/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2024-10-21 09:42:44,021 (56834/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2024-10-21 11:16:42,467 (88329/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-21 11:16:42,468 (88329/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-21 17:16:11,546 (38142/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-21 17:16:11,547 (38142/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-21 17:16:21,635 (38142/MainThread) pgcli.pgexecute ERROR - sql: '\\a', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\a\n        ^')
2024-10-21 17:16:21,638 (38142/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\a\n        ^\n'
2024-10-21 17:34:43,397 (39148/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-21 17:34:43,397 (39148/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-21 17:34:43,401 (39148/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-21 17:34:47,558 (39169/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-21 17:34:47,558 (39169/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 09:48:20,994 (26402/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 09:48:20,994 (26402/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 09:48:20,999 (26402/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-22 09:48:27,192 (26422/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 09:48:27,193 (26422/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 09:48:34,704 (26422/MainThread) pgcli.pgexecute ERROR - sql: 'x', error: SyntaxError('syntax error at or near "x"\nLINE 1: x\n        ^')
2024-10-22 09:48:34,706 (26422/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "x"\nLINE 1: x\n        ^\n'
2024-10-22 09:54:13,046 (27328/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 09:54:13,047 (27328/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 09:57:04,094 (27630/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 09:57:04,094 (27630/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 10:09:21,694 (31555/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 10:09:21,695 (31555/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 10:21:09,882 (38696/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 10:21:09,882 (38696/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 10:21:09,888 (38696/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-22 10:21:13,216 (38717/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 10:21:13,216 (38717/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-22 10:21:13,248 (38717/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  could not open file "global/pg_filenode.map": No such file or directory\n'
2024-10-22 10:22:01,067 (38800/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-22 10:22:01,068 (38800/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-28 09:39:52,794 (23507/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-28 09:39:52,794 (23507/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-28 09:41:01,294 (23711/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-28 09:41:01,294 (23711/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-28 09:51:49,084 (23711/MainThread) pgcli.main ERROR - sql: 'select * from projekt_inserat_process where einheiten_upload_count>0 limit 3;', error: StopIteration()
2024-10-28 09:51:49,090 (23711/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-28 09:52:26,839 (23711/MainThread) pgcli.main ERROR - sql: 'select * from projekt_inserat_process where einheiten_upload_count > 0 limit 3;', error: StopIteration()
2024-10-28 09:52:26,840 (23711/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-28 09:52:48,029 (23711/MainThread) pgcli.main ERROR - sql: 'select * from projekt_inserat_process where einheiten_upload_count is not null limit 3;', error: StopIteration()
2024-10-28 09:52:48,030 (23711/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-28 09:59:06,490 (25525/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-28 09:59:06,490 (25525/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-28 10:15:56,867 (25525/MainThread) pgcli.main ERROR - sql: "select * from projekt_inserat_process where id = '7f07f606-b540-4bbf-86d5-f7e152733e2a';", error: StopIteration()
2024-10-28 10:15:56,873 (25525/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-28 10:21:54,525 (25525/MainThread) pgcli.pgexecute ERROR - sql: "select process_record.id from projekt_inserat_process where id = '568d7dd3-5e3b-41f1-b5f9-6b0cd6c08f89'", error: UndefinedTable('missing FROM-clause entry for table "process_record"\nLINE 1: select process_record.id from projekt_inserat_process where ...\n               ^')
2024-10-28 10:21:54,529 (25525/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: missing FROM-clause entry for table "process_record"\nLINE 1: select process_record.id from projekt_inserat_process where ...\n               ^\n'
2024-10-29 08:41:57,056 (38780/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-29 08:41:57,057 (38780/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-29 08:41:57,062 (38780/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-29 08:42:02,562 (38811/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-29 08:42:02,562 (38811/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-30 08:59:52,931 (86498/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-30 08:59:52,931 (86498/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-30 08:59:56,342 (86498/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "more-backend"\n'
2024-10-30 08:59:58,066 (86532/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-30 08:59:58,066 (86532/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-30 11:09:17,923 (11951/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-30 11:09:17,924 (11951/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-30 11:16:34,823 (11951/MainThread) pgcli.main ERROR - sql: 'select * from projekt_inserat_process where einheiten_upload_count is not null limit 3;', error: StopIteration()
2024-10-30 11:16:34,827 (11951/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-30 11:17:05,366 (11951/MainThread) pgcli.main ERROR - sql: 'select * from projekt_inserat_process where einheiten_upload_count is not null;', error: StopIteration()
2024-10-30 11:17:05,367 (11951/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-10-30 11:19:35,533 (11951/MainThread) pgcli.main ERROR - sql: "select * from einheit where id = '392723d3-a258-480c-a308-cc038fa1c87c';", error: StopIteration()
2024-10-30 11:19:35,535 (11951/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-11 10:33:39,252 (11392/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-11 10:33:39,252 (11392/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-11 10:36:21,053 (11392/MainThread) pgcli.pgexecute ERROR - sql: 'select * from anlage where external_anlagennummer = 5651', error: UndefinedFunction('operator does not exist: character varying = integer\nLINE 1: select * from anlage where external_anlagennummer = 5651\n                                                          ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.')
2024-11-11 10:36:21,056 (11392/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedFunction: operator does not exist: character varying = integer\nLINE 1: select * from anlage where external_anlagennummer = 5651\n                                                          ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n'
2024-11-11 10:57:02,805 (15793/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-11 10:57:02,805 (15793/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 10:05:43,247 (9056/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 10:05:43,247 (9056/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 10:05:43,252 (9056/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-11-13 10:05:47,800 (9080/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 10:05:47,801 (9080/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 10:34:41,975 (14896/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 10:34:41,976 (14896/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 10:34:45,858 (14896/MainThread) pgcli.pgexecute ERROR - sql: 'PGDMP', error: SyntaxError('syntax error at or near "PGDMP"\nLINE 1: PGDMP\n        ^')
2024-11-13 10:34:45,858 (14896/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "PGDMP"\nLINE 1: PGDMP\n        ^\n'
2024-11-13 11:07:37,783 (23375/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 11:07:37,783 (23375/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 11:07:54,892 (23417/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 11:07:54,893 (23417/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 11:09:16,505 (23558/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 11:09:16,505 (23558/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 11:47:27,517 (30137/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 11:47:27,517 (30137/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 14:06:32,986 (46758/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 14:06:32,986 (46758/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 14:40:32,064 (51775/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 14:40:32,064 (51775/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 15:29:43,347 (61487/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-13 15:29:43,347 (61487/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-13 15:30:27,285 (61487/MainThread) pgcli.pgexecute ERROR - sql: '/x', error: SyntaxError('syntax error at or near "/"\nLINE 1: /x\n        ^')
2024-11-13 15:30:27,288 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /x\n        ^\n'
2024-11-13 15:35:49,215 (61487/MainThread) pgcli.pgexecute ERROR - sql: 'select unique process_type from process_record', error: SyntaxError('syntax error at or near "process_type"\nLINE 1: select unique process_type from process_record\n                      ^')
2024-11-13 15:35:49,216 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "process_type"\nLINE 1: select unique process_type from process_record\n                      ^\n'
2024-11-13 15:37:00,260 (61487/MainThread) pgcli.pgexecute ERROR - sql: "select * from process_record where process_type='EINHEIT_INSERAT' and bauteil_id not null limit 5", error: SyntaxError('syntax error at or near "not"\nLINE 1: ...ere process_type=\'EINHEIT_INSERAT\' and bauteil_id not null l...\n                                                             ^')
2024-11-13 15:37:00,261 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "not"\nLINE 1: ...ere process_type=\'EINHEIT_INSERAT\' and bauteil_id not null l...\n                                                             ^\n'
2024-11-13 15:37:22,062 (61487/MainThread) pgcli.main ERROR - sql: "select * from process_record where process_type='EINHEIT_INSERAT' and bauteil_id is not null limit 5;", error: StopIteration()
2024-11-13 15:37:22,063 (61487/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-13 15:40:05,351 (61487/MainThread) pgcli.pgexecute ERROR - sql: 'select unique process_type from process_record', error: SyntaxError('syntax error at or near "process_type"\nLINE 1: select unique process_type from process_record\n                      ^')
2024-11-13 15:40:05,352 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "process_type"\nLINE 1: select unique process_type from process_record\n                      ^\n'
2024-11-13 15:47:43,545 (61487/MainThread) pgcli.pgexecute ERROR - sql: "select * from process_record where bauteil_id = '", error: SyntaxError('unterminated quoted string at or near "\'"\nLINE 1: select * from process_record where bauteil_id = \'\n                                                        ^')
2024-11-13 15:47:43,546 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: unterminated quoted string at or near "\'"\nLINE 1: select * from process_record where bauteil_id = \'\n                                                        ^\n'
2024-11-13 15:47:46,595 (61487/MainThread) pgcli.pgexecute ERROR - sql: "select * from process_record where bauteil_id = '", error: SyntaxError('unterminated quoted string at or near "\'"\nLINE 1: select * from process_record where bauteil_id = \'\n                                                        ^')
2024-11-13 15:47:46,596 (61487/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: unterminated quoted string at or near "\'"\nLINE 1: select * from process_record where bauteil_id = \'\n                                                        ^\n'
2024-11-13 15:48:09,572 (61487/MainThread) pgcli.main ERROR - sql: "select * from process_record where bauteil_id = 'c7a08524-fd2e-4984-b34a-bf4713142ca8';", error: StopIteration()
2024-11-13 15:48:09,573 (61487/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-13 15:48:19,269 (61487/MainThread) pgcli.main ERROR - sql: "select * from process_record where bauteil_id = 'c7a08524-fd2e-4984-b34a-bf4713142ca8';", error: StopIteration()
2024-11-13 15:48:19,270 (61487/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-15 14:08:09,702 (67098/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-15 14:08:09,702 (67098/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-15 14:11:12,326 (67098/MainThread) pgcli.pgexecute ERROR - sql: 'select * from', error: SyntaxError('syntax error at end of input\nLINE 1: select * from\n                     ^')
2024-11-15 14:11:12,330 (67098/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from\n                     ^\n'
2024-11-15 14:15:43,749 (67098/MainThread) pgcli.pgexecute ERROR - sql: 'select id,', error: SyntaxError('syntax error at end of input\nLINE 1: select id,\n                  ^')
2024-11-15 14:15:43,752 (67098/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select id,\n                  ^\n'
2024-11-15 14:16:43,839 (67098/MainThread) pgcli.pgexecute ERROR - sql: 'select id, process_type, distinct bauteil_id from process_record', error: SyntaxError('syntax error at or near "distinct"\nLINE 1: select id, process_type, distinct bauteil_id from process_re...\n                                 ^')
2024-11-15 14:16:43,841 (67098/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "distinct"\nLINE 1: select id, process_type, distinct bauteil_id from process_re...\n                                 ^\n'
2024-11-18 09:51:57,052 (2650/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 09:51:57,052 (2650/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 09:58:35,272 (3592/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 09:58:35,273 (3592/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 10:04:17,401 (4223/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 10:04:17,401 (4223/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 10:04:19,927 (4223/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "more-backend"\n'
2024-11-18 10:04:23,522 (4245/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 10:04:23,522 (4245/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 10:09:57,144 (4245/MainThread) pgcli.pgexecute ERROR - sql: '\\w', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\w\n        ^')
2024-11-18 10:09:57,147 (4245/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\w\n        ^\n'
2024-11-18 10:15:42,642 (5382/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 10:15:42,642 (5382/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 10:15:45,452 (5382/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "more-backend"\n'
2024-11-18 10:15:48,414 (5423/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-18 10:15:48,415 (5423/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-18 13:17:19,285 (5423/MainThread) pgcli.pgexecute ERROR - sql: 'select vergabeart from process_record', error: UndefinedColumn('column "vergabeart" does not exist\nLINE 1: select vergabeart from process_record\n               ^')
2024-11-18 13:17:19,292 (5423/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "vergabeart" does not exist\nLINE 1: select vergabeart from process_record\n               ^\n'
2024-11-18 13:17:32,732 (5423/MainThread) pgcli.pgexecute ERROR - sql: 'select * from pro', error: UndefinedTable('relation "pro" does not exist\nLINE 1: select * from pro\n                      ^')
2024-11-18 13:17:32,734 (5423/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "pro" does not exist\nLINE 1: select * from pro\n                      ^\n'
2024-11-18 13:17:57,500 (5423/MainThread) pgcli.pgexecute ERROR - sql: 'select * from', error: SyntaxError('syntax error at end of input\nLINE 1: select * from\n                     ^')
2024-11-18 13:17:57,502 (5423/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from\n                     ^\n'
2024-11-19 09:27:20,348 (50503/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-19 09:27:20,348 (50503/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-19 09:27:20,352 (50503/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-11-19 09:27:33,463 (50559/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-19 09:27:33,464 (50559/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-19 09:27:42,688 (50559/MainThread) pgcli.pgexecute ERROR - sql: 'select id from', error: SyntaxError('syntax error at end of input\nLINE 1: select id from\n                      ^')
2024-11-19 09:27:42,691 (50559/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select id from\n                      ^\n'
2024-11-19 12:27:27,481 (6217/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-19 12:27:27,481 (6217/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-19 12:27:27,499 (6217/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: could not receive data from server: Connection refused\n'
2024-11-19 12:28:01,703 (6660/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-19 12:28:01,704 (6660/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-19 12:29:34,616 (6660/MainThread) pgcli.main ERROR - sql: 'select * from einheit where einheit_vergabeart_id is not null limit 2;', error: StopIteration()
2024-11-19 12:29:34,620 (6660/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-19 12:29:40,864 (6660/MainThread) pgcli.pgexecute ERROR - sql: 'select * from einheit where einheit_vergabeart_id not null', error: SyntaxError('syntax error at or near "not"\nLINE 1: select * from einheit where einheit_vergabeart_id not null\n                                                          ^')
2024-11-19 12:29:40,867 (6660/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "not"\nLINE 1: select * from einheit where einheit_vergabeart_id not null\n                                                          ^\n'
2024-11-19 12:29:47,962 (6660/MainThread) pgcli.main ERROR - sql: 'select * from einheit where einheit_vergabeart_id is not null;', error: StopIteration()
2024-11-19 12:29:47,963 (6660/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n        title, cur, headers, status, settings, self.explain_mode\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1851, in format_output\n    first_line = next(formatted)\nStopIteration\n'
2024-11-19 15:28:09,545 (23443/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-19 15:28:09,546 (23443/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-11-19 15:48:44,028 (23443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 741, in connect\n    passwd = click.prompt(\n        "Password for %s" % user,\n    ...<2 lines>...\n        type=str,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/click/termui.py", line 164, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/click/termui.py", line 147, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2024-11-25 11:28:45,943 (67231/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-11-25 11:28:45,944 (67231/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-30 16:45:19,631 (69309/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-30 16:45:19,631 (69309/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-30 16:45:27,058 (69309/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "10.224.64.5", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "10.224.64.5", port 5432 failed: FATAL:  password authentication failed for user "app_backend"\nconnection to server at "10.224.64.5", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.225.0.2", user "app_backend", database "backend", no encryption\n'
2025-01-30 16:45:32,390 (69337/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-30 16:45:32,390 (69337/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-30 16:45:37,709 (69337/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "10.224.64.5", port 5432 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "10.224.64.5", port 5432 failed: FATAL:  password authentication failed for user "app_backend"\nconnection to server at "10.224.64.5", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.225.0.2", user "app_backend", database "backend", no encryption\n'
2025-01-30 16:45:45,397 (69367/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-30 16:45:45,398 (69367/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
